version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops

    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped


  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9091:9090"

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  devops_project:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    volumes:
      - .m2:/root/.m2
    restart: always
    stdin_open: true
    tty: true
volumes:
  db: