version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    networks:
     mynetwork:
      ipv4_address: 172.18.0.2
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

  devops_project:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    volumes:
      - .m2:/root/.m2
    restart: always
    stdin_open: true
    tty: true
    networks:
        mynetwork:
          ipv4_address: 172.18.0.3  # Specify a different fixed IP address
volumes:
  db:
networks:
  mynetwork:
    driver: bridge
    ipam:
     driver: default
     config:
      - subnet: 172.18.0.0/16