version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
  devops_project:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - .m2:/root/.m2
    restart: always
  springboot-docker-compose-app-container:
      image: springboot-docker-compose-app:1
      build:
        context: ./
        dockerfile: Dockerfile
      volumes:
        - /data/springboot-docker-compose-app
      ports:
        - "8081:8081"
volumes:
  db: