version: "3.9"


services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/vagrant/datadir:/var/lib/mysql
  
  spring_app:
    container_name: devops_project
    image: akrimi11/devops_project
    restart: on-failure
    ports:
      - 8082:8082
    depends_on:
      - mysqldb