version: '3.1'
services:
  db:
    image: mysql
    container_name: base
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: iheb
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2  # Specify the desired fixed IP address
  prometheus:
    image: prom/prometheus

    ports:
      - "9091:9090"
  grafana:
      image: grafana/grafana

      ports:
        - "3001:3000"
  back:
    depends_on:
      - db
    build: ./
    restart: on-failure
    ports:
      - "8082:8082"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      mynetwork:
        ipv4_address: 172.18.0.3  # Specify a different fixed IP address


volumes:
  db:
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
